@startuml
'https://plantuml.com/sequence-diagram

title Update device details Sequence Diagram

autoactivate on
autonumber

actor "User" as User
participant ":DeviceController" as Ctrl
participant ":Helper" as Helper
participant ":repo:UserRepository" as userRepo
participant "user:User" as usr
participant "deviceService:DeviceService" as Svc
participant "subscriptionRepo:SubscriptionRepository" as subRepo
participant "device:Device" as device
participant "deviceRepo:DeviceRepository" as devRepo

activate User

User -> Ctrl: PUT/api/devices/update/:macAddr
Ctrl -> Helper: getUserByToken(request)
Helper --> Ctrl: userId
Ctrl -> userRepo: findById(userId)
userRepo --> Ctrl: user
Ctrl -> usr**: getAuthorities()
group alt if (user.role == "SUBSCRIBER")
    group alt if (ifMatchValue != null || !ifMatchValue.isEmpty()){
    Ctrl -> Svc: update(macAddress,resource,desiredVersion)
    Svc -> devRepo: findById(macAddress)
    devRepo --> Svc: device
    Svc -> device: update(desiredVersion, userId, resource.getDesignation() )
    alt if(currentVersion != desiredVersion)
        device -> device: setDesignation(resource.getDesignation())
        deactivate
        device -> device: setSubscriptionId(resource.getUserId())
    end
    device --> Svc: device
    deactivate device
    Svc -> devRepo: save(device)
    devRepo --> Svc: device
    Svc --> Ctrl: device
    end
end
Ctrl --> User: 200 OK

@enduml
