@startuml
'https://plantuml.com/sequence-diagram

title List Devices from a specific subscription System Sequence Diagram

autoactivate on
autonumber

actor "User" as User
participant ":RestAPI" as System

activate User

User -> System: GET/api/devices/user
System --> User: 200 Ok



@enduml
