@startuml
'https://plantuml.com/sequence-diagram

title List of Plans Sequence Diagram

autoactivate on
autonumber

actor "User" as User
participant ":PlanController" as Ctrl
participant ":Helper" as Helper
participant ":repo:UserRepository" as userRepo
participant "user:User" as usr
participant "planService:PlanService" as Svc
participant "repository:PlanRepository" as planRepo

activate User


User -> Ctrl: GET/api/plans
Ctrl -> Helper: getUserByToken(request)
Helper --> Ctrl: userId
Ctrl -> userRepo: findById(userId)
userRepo --> Ctrl: user
Ctrl -> usr**: getAuthorities()
alt if(user.role = "NEW_COSTUMER")
    Ctrl -> Svc: findAll()
    Svc -> planRepo: findAll()
    planRepo --> Svc: plan
    Svc --> Ctrl: plan
end
Ctrl --> User: 200 OK

@enduml


