@startuml
'https://plantuml.com/sequence-diagram

title List of Plans System Sequence Diagram

autoactivate on
autonumber

participant "ClientHttp" as User
participant ":PlansQuery" as System

activate User

User -> System: GET /api/plans
System -> System: findAll()
System --> User: 200 OK



@enduml
