@startuml
'https://plantuml.com/sequence-diagram

title Get plan's details System Sequence Diagram

autoactivate on
autonumber

actor "User" as User
participant ":RestAPI" as System

activate User

User -> System: GET/api/subscriptions/planDetails
System --> User: 200 ok
@enduml
