@startuml
'https://plantuml.com/sequence-diagram

title Create user account System Sequence Diagram

autoactivate on
autonumber

actor "User" as User
participant ":RestAPI" as System

activate User

User -> System: POST/public/login
System --> User: 201 Created
@enduml
