@startuml
'https://plantuml.com/sequence-diagram

title Migrate subscribers from one plan to another Sequence Diagram

autoactivate on
autonumber

actor "User" as User
participant ":SubscriptionController" as Ctrl
participant ":Helper" as Helper
participant ":repo:UserRepository" as userRepo
participant "user:User" as usr
participant "service:SubscriptionService" as ServiceSubscription
participant "repo:PlanRepository" as PlanRepo
participant "repo:SubscriptionRepository" as SubRepo
participant "repo:DeviceRepository" as DeviceRepo
participant "subscription:Subscription" as Subscription

activate User

User -> Ctrl: PATCH/api/subscriptions/migrate/{planName}
Ctrl -> Helper: getUserByToken(request)
Helper --> Ctrl: userId
Ctrl -> userRepo: findById(userId)
userRepo --> Ctrl: user
Ctrl -> usr**: getAuthorities()
alt if(user.role = "MARKETING_DIRECTOR")
    Ctrl -> ServiceSubscription: migrate(planName, resource)
    ServiceSubscription -> PlanRepo: findById(planName)
    PlanRepo --> ServiceSubscription: plan
    ServiceSubscription -> PlanRepo: findByPlanName(resource.getNewPlanName())
    PlanRepo --> ServiceSubscription: maybePlan
    ServiceSubscription -> SubRepo: findByPlanName(planName)
    SubRepo --> ServiceSubscription: subscriptions
    alt for(Subscription subscription : subscriptions)
        ServiceSubscription -> DeviceRepo: findByUserId(subscription.getUserId())
        DeviceRepo --> ServiceSubscription: devices
        ServiceSubscription -> DeviceRepo: deleteAll(devices)
        ServiceSubscription -> Subscription**: subscription.setPlanName(resource.getNewPlanName())
        ServiceSubscription -> Subscription: subscription.setCurrentDevices(0)
        ServiceSubscription -> SubRepo: save(subscription)
    end
    ServiceSubscription --> Ctrl: subscriptions
end
Ctrl --> User: 200 Ok

@enduml
