@startuml
'https://plantuml.com/sequence-diagram

title Price History System Sequence Diagram

autoactivate on
autonumber

actor "User" as User
participant ":RestAPI" as System

activate User

User -> System: GET/api/plans/{planName}
System --> User: 200 OK



@enduml
