@startuml
'https://plantuml.com/sequence-diagram

title Switch plan System Sequence Diagram

autoactivate on
autonumber

actor "User" as User
participant ":RestAPI" as System

activate User

User -> System: PATCH/api/subscriptions/switchPlan
System --> User: 200 Ok
@enduml
