@startuml
'https://plantuml.com/sequence-diagram

title Reactivate a subscription System Sequence Diagram

autoactivate on
autonumber

actor "User" as User
participant ":RestAPI" as System

activate User

User -> System: PUT/api/subscriptions/reactivate
System --> User: 200 ok
@enduml
