@startuml
'https://plantuml.com/sequence-diagram

title  Get Revenue

autoactivate on
autonumber

actor "User" as User
participant ":RestAPI" as System

activate User

User -> System: GET /api/dashboard/revenue?plan
System --> User: 200 ok
@enduml
